import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MION - Образовательный портал #1 | Профессиональное образование доступное каждому</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
      </main>

      
    </div>
  )
}
export async function getServerSideProps({req, params}) {
  return {
    redirect: {
      destination: '/ru',
      permanent: true,
    },
  }
}
export default Home
