import Head from 'next/head'
import Main from '../../../layouts/main/Main'
import styles from '../../../styles/Home.module.css'
import { NET } from './../../../network';
import ProtectedMain from './../../../common/decorators/ProtectedMain';
import ProfileTarifView from '../../../views/main/ProfileTarifView';

function ProfileTarif({
  data
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Тарифы | MION | Мион</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/animate.css@3.5.2/animate.min.css"/>
      </Head>

      <main className={styles.main}>
        <ProtectedMain>
          <Main>
            <ProfileTarifView
                data={data}
            />
          </Main>
        </ProtectedMain>
      </main>

      
    </div>
  )
}

export async function getServerSideProps({req, params}) {
  const headers = {
      headers: {
          'X-Requested-With': 'XMLHttpRequest',
          'Content-Type': 'application/json;charset=UTF-8',
          // Authorization: `Bearer ${userToken}`
      },
      method: 'GET'
  };

  const resData = await fetch(
      `${NET.BACK_URL}/mion/companies-counter`,
      headers,
  );
  const data = await resData.json()


  return {
    props: {
      data: JSON.parse(JSON.stringify(data)),
      // modules: JSON.parse(JSON.stringify(modules)),
      // company: JSON.parse(JSON.stringify(company))
    } // will be passed to the page component as props
  }
}

export default ProfileTarif
